### ISSUE TITLE
[ aws cli ] about aws cli version :)

### ISSUE THREAD

**Issue by guan840912** [robertd/alpine-aws-cdk#7]
Hi Robert ~~
this is an awesome mind to use alpine cdk env , but one question why not install awscli v2 ?! 😳

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html

**Comment by robertd** [comment]
Hi Neil,

I was just piggybacking on pip to install aws-cli for me. I'll look into updating this to use aws-cli v2.

**Comment by robertd** [comment]
@guan840912 It looks like awscli2 is not available on pip (see https://github.com/aws/aws-cli/issues/4947#issuecomment-586046886).

I'll probably install awscli2 following these instructions: official https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-install ... stay tuned 👍

**Comment by robertd** [comment]
@guan840912  I ended up following this guide (https://github.com/aws/aws-cli/issues/3553#issuecomment-615149941) as awscli v2 is not officially supported on alpine.

I just re-tagged and re-deployed `1.72.0` docker image. Give it a try and let me know how it goes.
