### ISSUE TITLE
Missing image versions on DockerHub

### ISSUE THREAD

**Issue by Try431** [robertd/alpine-aws-cdk#8]
Hey there - thanks for the work you've put into maintaining this! 

I've been using the `robertd/alpine-aws-cdk:1.116.0` image for some projects, but it started breaking. I looked at the DockerHub page, and `1.115.0` is now the latest versioned image tag you have up on there. Do you think you'd be able to throw up the other versions on Docker Hub?

Thank you!

**Comment by iSenne85** [comment]
@Try431 I've created my own image (couldn't wait on @robertd unfortunately)

If you want to use it, check out https://hub.docker.com/r/deinternetjongens/aws-cdk (readme and github comming)

Hoping Robert will pick it up soon
